In [12]:
import numpy as np
import pandas as pd
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer

In [13]:
data = pd.read_csv(r"D:\Shrey\CETPA\Machine Learning\Data Sets\Market.csv")
data

    Unnamed: 0  Year  Month  Interest_Rate  Unemployment_Rate  Price
0            0  2017     12           2.75                5.3   1464
1            1  2017     11           2.50                5.3   1394
2            2  2017     10           2.50                5.3   1357
3            3  2017      9           2.50                5.3   1293
4            4  2017      8           2.50                5.4   1256
5            5  2017      7           2.50                5.6   1254
6            6  2017      6           2.50                5.5   1234
7            7  2017      5           2.25                5.5   1195
8            8  2017      4           2.25                5.5   1159
9            9  2017      3           2.25                5.6   1167
10          10  2017      2           2.00                5.7   1130
11          11  2017      1           2.00                5.9   1075
12          12  2016     12           2.00                6.0   1047
13          13  2016     11           1.75                5.9    965
14          14  2016     10           1.75                5.8    943
15          15  2016      9           1.75                6.1    958
16          16  2016      8           1.75                6.2    971
17          17  2016      7           1.75                6.1    949
18          18  2016      6           1.75                6.1    884
19          19  2016      5           1.75                6.1    866
20          20  2016      4           1.75                5.9    876
21          21  2016      3           1.75                6.2    822
22          22  2016      2           1.75                6.2    704
23          23  2016      1           1.75                6.1    719

In [14]:
x = data.values[:,1:5]
x

array([[2.017e+03, 1.200e+01, 2.750e+00, 5.300e+00],
       [2.017e+03, 1.100e+01, 2.500e+00, 5.300e+00],
       [2.017e+03, 1.000e+01, 2.500e+00, 5.300e+00],
       [2.017e+03, 9.000e+00, 2.500e+00, 5.300e+00],
       [2.017e+03, 8.000e+00, 2.500e+00, 5.400e+00],
       [2.017e+03, 7.000e+00, 2.500e+00, 5.600e+00],
       [2.017e+03, 6.000e+00, 2.500e+00, 5.500e+00],
       [2.017e+03, 5.000e+00, 2.250e+00, 5.500e+00],
       [2.017e+03, 4.000e+00, 2.250e+00, 5.500e+00],
       [2.017e+03, 3.000e+00, 2.250e+00, 5.600e+00],
       [2.017e+03, 2.000e+00, 2.000e+00, 5.700e+00],
       [2.017e+03, 1.000e+00, 2.000e+00, 5.900e+00],
       [2.016e+03, 1.200e+01, 2.000e+00, 6.000e+00],
       [2.016e+03, 1.100e+01, 1.750e+00, 5.900e+00],
       [2.016e+03, 1.000e+01, 1.750e+00, 5.800e+00],
       [2.016e+03, 9.000e+00, 1.750e+00, 6.100e+00],
       [2.016e+03, 8.000e+00, 1.750e+00, 6.200e+00],
       [2.016e+03, 7.000e+00, 1.750e+00, 6.100e+00],
       [2.016e+03, 6.000e+00, 1.750e+00, 6.100e+00],
       [2.016e+03, 5.000e+00, 1.750e+00, 6.100e+00],
       [2.016e+03, 4.000e+00, 1.750e+00, 5.900e+00],
       [2.016e+03, 3.000e+00, 1.750e+00, 6.200e+00],
       [2.016e+03, 2.000e+00, 1.750e+00, 6.200e+00],
       [2.016e+03, 1.000e+00, 1.750e+00, 6.100e+00]])

In [15]:
y = data["Price"]
y

0     1464
1     1394
2     1357
3     1293
4     1256
5     1254
6     1234
7     1195
8     1159
9     1167
10    1130
11    1075
12    1047
13     965
14     943
15     958
16     971
17     949
18     884
19     866
20     876
21     822
22     704
23     719
Name: Price, dtype: int64

In [16]:
#encoding categorial data
labelencoder = LabelEncoder()

In [17]:
x[:,0] = labelencoder.fit_transform(x[:,0])
a = x[:,0]
a

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0.])

In [11]:
onehotencoder = OneHotEncoder(categorical_features = [2])
onehotencoder

TypeError: __init__() got an unexpected keyword argument 'categorical_features'